{% set version = "3.6.1" %}

package:
  name: pytest-xdist
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-xdist/pytest_xdist-{{ version }}.tar.gz
  sha256: ead156a4db231eec769737f57668ef58a2084a34b2e55c4a8fa20d861107300d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.2
    - setuptools-scm >=6.2.3
  run:
    - execnet >=2.1
    - pytest >=7.0.0
    - python >=3.8
  run_constrained:
    - psutil >=3.0

test:
  imports:
    - xdist
  files:
    - dummy_test.py
  requires:
    - pip
  commands:
    - pip check
    - pytest -n2 dummy_test.py

about:
  home: https://github.com/pytest-dev/pytest-xdist
  license: MIT
  license_file: LICENSE
  summary: py.test xdist plugin for distributed testing and loop-on-failing modes
  dev_url: https://github.com/pytest-dev/pytest-xdist

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
